---
name: WiX3
version: 0.007
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
abstract: Objects useful for generating Windows Installer XML files.
license: perl
resources:
  DLSIP: http://search.cpan.org/dlsip?apdOp
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WiX3
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/WiX3/
build_requires:
  Test::More: 0.61
  Test::UseAllModules: 0.12
requires:
  Data::UUID: 1.202
  Exception::Class: 1.29
  List::MoreUtils: '>= 0.22, != 0.23, != 0.24'
  Moose: 0.86
  MooseX::AttributeHelpers: 0.19
  MooseX::LogDispatch: 1.2000
  MooseX::NonMoose: 0.05
  MooseX::Singleton: 0.19
  MooseX::Types: 0.16
  MooseX::Types::Moose: 0
  Params::Util: 1.00
  Readonly: 1.03
  Regexp::Common: 2.122
  perl: 5.008001
recommends:
  MIME::Lite: 3.020
  Readonly::XS: 1.05
configure_requires:
  Module::Build: 0.33
provides:
  WiX3:
    file: lib/WiX3.pm
    version: 0.007
  WiX3::Exceptions:
    file: lib/WiX3/Exceptions.pm
    version: 0.007
  WiX3::Role::Traceable:
    file: lib/WiX3/Role/Traceable.pm
    version: 0.007
  WiX3::Traceable:
    file: lib/WiX3/Traceable.pm
    version: 0.007
  WiX3::XML::Component:
    file: lib/WiX3/XML/Component.pm
    version: 0.007
  WiX3::XML::ComponentRef:
    file: lib/WiX3/XML/ComponentRef.pm
    version: 0.007
  WiX3::XML::CreateFolder:
    file: lib/WiX3/XML/CreateFolder.pm
    version: 0.007
  WiX3::XML::Directory:
    file: lib/WiX3/XML/Directory.pm
    version: 0.007
  WiX3::XML::DirectoryRef:
    file: lib/WiX3/XML/DirectoryRef.pm
    version: 0.007
  WiX3::XML::Environment:
    file: lib/WiX3/XML/Environment.pm
    version: 0.007
  WiX3::XML::Feature:
    file: lib/WiX3/XML/Feature.pm
    version: 0.007
  WiX3::XML::FeatureRef:
    file: lib/WiX3/XML/FeatureRef.pm
    version: 0.007
  WiX3::XML::File:
    file: lib/WiX3/XML/File.pm
    version: 0.007
  WiX3::XML::Fragment:
    file: lib/WiX3/XML/Fragment.pm
    version: 0.007
  WiX3::XML::Fragment::CreateFolder:
    file: lib/WiX3/XML/Fragment/CreateFolder.pm
    version: 0.007
  WiX3::XML::Icon:
    file: lib/WiX3/XML/Icon.pm
    version: 0.007
  WiX3::XML::RemoveFolder:
    file: lib/WiX3/XML/RemoveFolder.pm
    version: 0.007
  WiX3::XML::Role::Fragment:
    file: lib/WiX3/XML/Role/Fragment.pm
    version: 0.007
  WiX3::XML::Role::GeneratesGUID:
    file: lib/WiX3/XML/Role/GeneratesGUID.pm
    version: 0.007
  WiX3::XML::Role::Tag:
    file: lib/WiX3/XML/Role/Tag.pm
    version: 0.007
  WiX3::XML::Role::TagAllowsChildTags:
    file: lib/WiX3/XML/Role/TagAllowsChildTags.pm
    version: 0.007
  WiX3::XML::Shortcut:
    file: lib/WiX3/XML/Shortcut.pm
    version: 0.007
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
